# Generated by Django 2.2.5 on 2020-10-27 11:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=140)),
                ('toilets', models.IntegerField()),
                ('showerbooths', models.IntegerField()),
                ('operdays', models.DateField()),
                ('booklinks', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
