# Generated by Django 2.2.5 on 2020-10-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20201027_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='place',
            name='amenities',
            field=models.ManyToManyField(to='places.Amenity'),
        ),
        migrations.AddField(
            model_name='place',
            name='etcs',
            field=models.ManyToManyField(to='places.ETC'),
        ),
        migrations.AddField(
            model_name='place',
            name='facilities',
            field=models.ManyToManyField(to='places.Facility'),
        ),
    ]
