# Generated by Django 2.2.5 on 2020-10-27 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0004_auto_20201027_2225'),
        ('favs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favs',
            new_name='Fav',
        ),
    ]
