# Generated by Django 2.2.5 on 2020-11-02 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favs', '0002_auto_20201028_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='favs', to='places.Place'),
        ),
        migrations.AlterField(
            model_name='fav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favs', to=settings.AUTH_USER_MODEL),
        ),
    ]
